### ISSUE TITLE
Your First Application example wrong?

### ISSUE THREAD

**Issue by sayrer** [mjackson/strata#26]
I tried the "Your First Application" code sample and got an exception.

```
TypeError: Object #<Builder> has no method 'get'
at Object.<anonymous> (app.js:10:5)
at Module._compile (module.js:443:26)
at Object..js (module.js:461:10)
at Module.load (module.js:350:32)
at Function._load (module.js:308:12)
at Array.0 (module.js:481:10)
at EventEmitter._tickCallback (node.js:188:41)
```

The hello world example from the Applications page works fine.

**Comment by mjackson** [comment]
Ah, yes. The website is a bit behind. Updating it now.

**Comment by mjackson** [comment]
Voilà! Just released Strata version 0.12.0 and updated the website to reflect the changes.

**Comment by sayrer** [comment]
thanks, working great

**Comment by mjackson** [comment]
Awesome. Please let me know if you run into any other snags.
