### ISSUE TITLE
"TypeError: Bad file descriptor argument error" in helloworld app

### ISSUE THREAD

**Issue by ilkka** [mjackson/strata#7]
I built Node 0.4.12 from source, installed strata 0.5.12 with npm and copied the hello world app from the manual. This is the output of trying to run it with strata:

```
$ strata app.js

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
TypeError: Bad file descriptor argument
    at Server.address (net.js:1129:10)
    at createServer (/home/ilkka/node/lib/node_modules/strata/lib/index.js:97:23)
    at Object.run (/home/ilkka/node/lib/node_modules/strata/lib/index.js:46:18)
    at Object.<anonymous> (/home/ilkka/node/lib/node_modules/strata/bin/strata:80:29)
    at Module._compile (module.js:411:26)
    at Object..js (module.js:417:10)
    at Module.load (module.js:343:31)
    at Function._load (module.js:302:12)
    at Array.<anonymous> (module.js:430:10)
    at EventEmitter._tickCallback (node.js:126:26)
```

All the tests are green and basic node.js stuff seems to work fine.

**Comment by mjackson** [comment]
Thanks for reporting this! This is a regression. Fixed in [this commit](https://github.com/mjijackson/strata/commit/2501a05a8d45d640f5b606692298300fb4173636).

**Comment by ilkka** [comment]
works great now, thanks!
