### ISSUE TITLE
"ReferenceError: error is not defined" error in error handling example

### ISSUE THREAD

**Issue by ilkka** [mjackson/strata#8]
I'm up to the "Error handling" part of the Errors chapter in the manual, trying out the example that handles errors in the `req.params` callback. If I POST valid JSON to the app it works fine and prints the result, but if I POST invalid JSON, trying to invoke the error handler, the app exits with a backtrace. Here's the POST command line:

```
$ curl -v -H "Content-Type: application/json" --data '{"a";asdfa:"b"}' http://localhost:1982
* About to connect() to localhost port 1982 (#0)
*   Trying 127.0.0.1... connected
* Connected to localhost (127.0.0.1) port 1982 (#0)
> POST / HTTP/1.1
> User-Agent: curl/7.21.6 (i686-pc-linux-gnu) libcurl/7.21.6 OpenSSL/1.0.0e zlib/1.2.3.4 libidn/1.22 librtmp/2.3
> Host: localhost:1982
> Accept: */*
> Content-Type: application/json
> Content-Length: 15
> 
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
* Closing connection #0
```

And here's what Strata prints:

```
node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
ReferenceError: error is not defined
    at Object.handleError (/home/ilkka/node/lib/node_modules/strata/lib/index.js:217:5)
    at /home/ilkka/src/node/stratatest/app.js:15:27
    at /home/ilkka/node/lib/node_modules/strata/lib/request.js:549:21
    at BufferedStream.<anonymous> (/home/ilkka/node/lib/node_modules/strata/lib/request.js:438:17)
    at BufferedStream.emit (events.js:81:20)
    at Array.tick (/home/ilkka/node/lib/node_modules/strata/lib/bufferedstream.js:174:18)
    at EventEmitter._tickCallback (node.js:126:26)
```

This is on Strata v0.5.13 now.

**Comment by mjackson** [comment]
Thanks for catching yet another regression! This is fixed [here](https://github.com/mjijackson/strata/commit/3442330bd49fb59211fcaf63a9020a00a4215a79). I'm making sure to write tests for all these cases as they occur so I can be sure not to regress in the future.

**Comment by ilkka** [comment]
hey, no probs, I'm having fun :)
